[pytest]
markers =
    ollama: marks tests as requiring ollama
    browser: marks tests as requiring playwrite browser, add --browser to enable
    external: marks tests as reaching out to Internet sources
    serial
